#ifndef __MYCLASS_ITEM
#define __MYCLASS_ITEM

#ifndef IS_OSX
#include <SDL2/SDL_image.h>
#else
#include <SDL2_image/SDL_image.h>
#endif

#include <string.h>

#define sizeX 32
#define sizeY 32

class Item {
	public:
		Item();
		~Item();
		Item(SDL_Surface * items, int id, char * name, int value, int rarity, int unlock);
		int getId();
		char* getName();
		int getRarity();
		int getUnlock();
		int getValue();
		SDL_Surface * getSprite();
	private:
		int id;
		char name[50];
		int value;
		int rarity;
		int unlock;
		SDL_Surface * sprite;
};
#endif


/*
new Item(0,"Alphabet Cristallin");
new Item(1,"Bouclidur en or");
new Item(2,"Bouclidur argenté");
new Item(3,"Ballon de banquise");
new Item(4,"Lampe Fétvoveu");
new Item(5,"Lampe Léveussonfé");
new Item(6,"Paix intérieure");
new Item(7,"Basket IcePump");
new Item(8,"Etoile des neiges");
new Item(9,"Mauvais-oeil");
new Item(10,"Téléphone-phone-phone");
new Item(11,"Parapluie rouge");
new Item(12,"Parapluie bleu");
new Item(13,"Cass-Tet");
new Item(14,"Délice hallucinogène bleu");
new Item(15,"Champignon rigolo rouge");
new Item(16,"Figonassée grimpante");
new Item(17,"Petit Waoulalu des bois");
new Item(18,"Pissenlit tropical");
new Item(19,"Tournelune");
new Item(20,"Coffre d\'Anarchipel");
new Item(21,"Enceinte Bessel-Son");
new Item(22,"Vieille chaussure trouée");
new Item(23,"Boule cristalline");
new Item(24,"Hippo-flocon");
new Item(25,"Flamme froide");
new Item(26,"Ampoule 30 watts");
new Item(27,"Porte-grenouilles");
new Item(28,"Bibelot en argent");
new Item(29,"Bague \'Thermostat 8\'");
new Item(30,"Lunettes tournantes bleues");
new Item(31,"Lunettes renversantes rouges");
new Item(32,"As de pique");
new Item(33,"As de trêfle");
new Item(34,"As de carreau");
new Item(35,"As de coeur");
new Item(36,"Ig\'or");
new Item(37,"Collier rafraîchissant");
new Item(38,"Totem des dinoz");
new Item(39,"Tête de granit lestée de plomb");
new Item(40,"Sagittaire");
new Item(41,"Capricorne");
new Item(42,"Lion");
new Item(43,"Taureau");
new Item(44,"Balance");
new Item(45,"Bélier");
new Item(46,"Scorpion");
new Item(47,"Cancer");
new Item(48,"Verseau");
new Item(49,"Gémeaux");
new Item(50,"Poisson");
new Item(51,"Vierge");
new Item(52,"Elixir du Sagittaire");
new Item(53,"Elixir du Capricorne");
new Item(54,"Elixir du Lion");
new Item(55,"Elixir du Taureau");
new Item(56,"Elixir de la Balance");
new Item(57,"Elixir du Bélier");
new Item(58,"Elixir du Scorpion");
new Item(59,"Elixir du Cancer");
new Item(60,"Elixir du Verseau");
new Item(61,"Elixir des Gémeaux");
new Item(62,"Elixir du Poisson");
new Item(63,"Elixir de la Vierge");
new Item(64,"Arc-en-miel");
new Item(65,"Bouée canard");
new Item(66,"Branche de Kipik");
new Item(67,"Anneau de Guillaume Tell");
new Item(68,"Bougie");
new Item(69,"Koulraoule des îles");
new Item(70,"Trêfle commun");
new Item(71,"Chaud devant !");
new Item(72,"Chapeau de Mage-Gris");
new Item(73,"Feuille de sinopée");
new Item(74,"Esprit de l\'orange");
new Item(75,"Esprit de la pluie");
new Item(76,"Esprit des arbres");
new Item(77,"Lucidjané à crête bleue");
new Item(78,"Filandreux rougeoyant");
new Item(79,"Poisson empereur");
new Item(80,"Escargot Poussépa");
new Item(81,"Perle nacrée des murlocs");
new Item(82,"Jugement avant-dernier");
new Item(83,"Jugement dernier");
new Item(84,"Talisman scorpide");
new Item(85,"Baton tonnerre");
new Item(86,"Surprise de paille");
new Item(87,"Larve d\'oenopterius");
new Item(88,"Pokuté");
new Item(89,"Oeuf de Tzongre");
new Item(90,"Fulguro pieds-en-mousse");
new Item(91,"Couvre-chef de Luffy");
new Item(92,"Chapeau violin");
new Item(93,"Boit\'a\'messages");
new Item(94,"Anneau Antok");
new Item(95,"Cagnotte de Tuberculoz");
new Item(96,"Perle flamboyante");
new Item(97,"Perle vertillante");
new Item(98,"Grosse pé-perle ");
new Item(99,"Poils de Chourou");
new Item(100,"Pocket-Guu");
new Item(101,"Colis surprise");
new Item(102,"La Carotte d\'Igor");
new Item(103,"Vie palpitante");
new Item(104,"Vie aventureuse");
new Item(105,"Vie épique");
new Item(106,"Livre des champignons");
new Item(107,"Livre des étoiles");
new Item(108,"Parapluie Frutiparc");
new Item(109,"Flocon simple");
new Item(110,"Flocon bizarre");
new Item(111,"Flocon ENORME !");
new Item(112,"Pioupiou carnivore");
new Item(113,"Cape de Tuberculoz");
new Item(114,"Mode Mario");
new Item(115,"Casque de Volleyfest");
new Item(116,"Joyau d\'Ankhel");
new Item(117,"Clé de Gordon");
new Item(1000,"Cristaux d\'Hammerfest");
new Item(1001,"Pain à la viande");
new Item(1002,"Canne de Bobble");
new Item(1003,"Bonbon Berlinmauve");
new Item(1004,"Bonbon Chamagros");
new Item(1005,"Bonbon rosamelle-praline");
new Item(1006,"Sucette aux fruits bleus");
new Item(1007,"Sucette chlorophylle");
new Item(1008,"Diamant Oune-difaïned");
new Item(1009,"Oeil de tigre");
new Item(1010,"Jade de 12kg");
new Item(1011,"Reflet-de-lune");
new Item(1012,"Surprise de Cerises");
new Item(1013,"Muffin aux cailloux");
new Item(1014,"Gelée des bois");
new Item(1015,"Suprême aux framboises");
new Item(1016,"Petit pétillant");
new Item(1017,"Pierres du Changement");
new Item(1018,"Glace Fraise");
new Item(1019,"Coupe Glacée");
new Item(1020,"Noodles");
new Item(1021,"Poulet Surgelé");
new Item(1022,"Liquide bizarre");
new Item(1023,"Gros acidulé");
new Item(1024,"Liquide étrange");
new Item(1025,"Oeuf cru");
new Item(1026,"Gland gnan-gnan");
new Item(1027,"Réglisse rouge");
new Item(1028,"Oeuf Au Plat");
new Item(1029,"Saucisse piquée");
new Item(1030,"Cerise-apéro confite");
new Item(1031,"Fromage piqué");
new Item(1032,"Olive pas mûre");
new Item(1033,"Olive noire");
new Item(1034,"Oeil de pomme");
new Item(1035,"Blob intrusif");
new Item(1036,"Gouda mou");
new Item(1037,"Poulpi empalé");
new Item(1038,"Olive oubliée");
new Item(1039,"Monsieur radis");
new Item(1040,"Sushi thon");
new Item(1041,"Sucette acidulée");
new Item(1042,"Délice d\'Aralé");
new Item(1043,"Sorbet au plastique");
new Item(1044,"Manda");
new Item(1045,"Pétale mystérieuse");
new Item(1046,"Gump");
new Item(1047,"Bleuet");
new Item(1048,"Rougeoyant");
new Item(1049,"Verdifiant");
new Item(1050,"KassDent");
new Item(1051,"Pièce d\'or secrète");
new Item(1052,"Sou d\'argent");
new Item(1053,"Sou d\'or");
new Item(1054,"Gros tas de sous");
new Item(1055,"Boisson kipik");
new Item(1056,"Doigts-de-tuberculoz");
new Item(1057,"Pizza de Donatello");
new Item(1058,"Canelé du sud-ouest");
new Item(1059,"Eclair noisette choco caramel et sucre");
new Item(1060,"Bleuette rouge");
new Item(1061,"Perroquet décapité en sauce");
new Item(1062,"Morvo-morphe");
new Item(1063,"Fraise Tagada");
new Item(1064,"Car-En-Sac");
new Item(1065,"Dragibus");
new Item(1066,"Krokodile");
new Item(1067,"Demi Cocobats");
new Item(1068,"Happy Cola");
new Item(1069,"Cacahuete secrète");
new Item(1070,"P\'tit fantome");
new Item(1071,"Cookie deshydraté");
new Item(1072,"Arbuche de noël");
new Item(1073,"Piment farceur");
new Item(1074,"Soja Max IceCream");
new Item(1075,"Bouquet de steack");
new Item(1076,"Daruma-Pastèque");
new Item(1077,"Graine de tournesol");
new Item(1078,"Croissant confit");
new Item(1079,"Haricot paresseux");
new Item(1080,"Lapin-choco");
new Item(1081,"Biloo");
new Item(1082,"Graine de pechume en gelée");
new Item(1083,"Sombrino aux amandes");
new Item(1084,"Emi-Praline");
new Item(1085,"Frogmaliet aux pepites de chocolat");
new Item(1086,"Yumi au café");
new Item(1087,"Bouchée mielleuse nappée au gel de Vodka");
new Item(1088,"Escargot au chocolat persillé");
new Item(1089,"Fossile de cacao marbré au fois gras");
new Item(1090,"Cerisot mariné a la bière");
new Item(1091,"Jambon de Bayonne");
new Item(1092,"Saucisson entamé");
new Item(1093,"Raide red reste");
new Item(1094,"Torchon madrangeais au sirop d\'érable");
new Item(1095,"Saucisson de marcassin sauvage");
new Item(1096,"Tranches de Jaret de Kangourou");
new Item(1097,"Saucissaille de St-Morgelet");
new Item(1098,"Paté d\'ongles au truffes");
new Item(1099,"Saucisson maudit scellé");
new Item(1100,"Manquereau-sauce-au-citron");
new Item(1101,"Mini-saucisses en boite");
new Item(1102,"Haricots blanc");
new Item(1103,"Lychees premier prix");
new Item(1104,"Zion\'s Calamar");
new Item(1105,"Aubergines au sirop");
new Item(1106,"Camembert");
new Item(1107,"Emmental");
new Item(1108,"Fromage verni");
new Item(1109,"Roquefort");
new Item(1110,"Fromage frais vigné");
new Item(1111,"Pâte dessert fromagée");
new Item(1112,"Saladou");
new Item(1113,"Poire d\'eau");
new Item(1114,"Cacahuète mauve et juteuse");
new Item(1115,"Pommes de pierre");
new Item(1116,"Patates douces");
new Item(1117,"Matraque bio");
new Item(1118,"Tomate pacifique");
new Item(1119,"Radix");
new Item(1120,"Haricots verts");
new Item(1121,"Pomme Sapik");
new Item(1122,"Pomme Sapu");
new Item(1123,"Echalottes");
new Item(1124,"Sel rieur");
new Item(1125,"Poivron vert");
new Item(1126,"Poivron jaune");
new Item(1127,"Poivron rouge");
new Item(1128,"Brocolis digérés");
new Item(1129,"Grappe de Radix");
new Item(1130,"Lance-poix");
new Item(1131,"Haricots blancs");
new Item(1132,"Poires d\'eau en grappe");
new Item(1133,"Artifroid");
new Item(1134,"Choux-flou");
new Item(1135,"Chourou");
new Item(1136,"Pom pom pom..");
new Item(1137,"Hollandais");
new Item(1138,"Fondant XXL au choco-beurre");
new Item(1139,"Pétillante");
new Item(1140,"Warpoquiche");
new Item(1141,"Brioche dorée");
new Item(1142,"Café de fin de projet");
new Item(1143,"Laxatif aux amandes");
new Item(1144,"Smiley croquant");
new Item(1145,"Barquette de lave");
new Item(1146,"Nonoix");
new Item(1147,"Amande croquante");
new Item(1148,"Noisette");
new Item(1149,"Noodles crus");
new Item(1150,"Brioche vapeur");
new Item(1151,"Tartine chocolat-noisette");
new Item(1152,"Tartine hémoglobine");
new Item(1153,"Tartine à l\'orange collante");
new Item(1154,"Tartine au miel");
new Item(1155,"Lombric nature");
new Item(1156,"Grenade de chantilly");
new Item(1157,"Profies très drôles");
new Item(1158,"Chouchocos");
new Item(1159,"Blob périmé");
new Item(1160,"Bonbon Hélène-fraiche");
new Item(1161,"Nem aux anchois");
new Item(1162,"Surimi pamplemousse");
new Item(1163,"Poulpi à l\'encre");
new Item(1164,"Curly");
new Item(1165,"Tartelette framboise");
new Item(1166,"Oeuf de Poire");
new Item(1167,"Truffe collante sans goût");
new Item(1168,"Sardines");
new Item(1169,"Etoile Toulaho");
new Item(1170,"Transformer en sucre");
new Item(1171,"Kitchissime");
new Item(1172,"Igorocop");
new Item(1173,"Tidouli didi");
new Item(1174,"Dalek ! Exterminate !");
new Item(1175,"Robo-malin");
new Item(1176,"Johnny 6");
new Item(1177,"Biscuit Transformer");
new Item(1178,"Statue: Citron Sorbex");
new Item(1179,"Statue: Bombino");
new Item(1180,"Statue: Poire Melbombe");
new Item(1181,"Statue: Tagada");
new Item(1182,"Statue: Sapeur-kiwi");
new Item(1183,"Statue: Bondissante");
new Item(1184,"Statue: Ananargeddon");
new Item(1185,"Anneau hérissé");
new Item(1190,"Passe-partout en bois");
new Item(1191,"Clé de Rigor Dangerous");
new Item(1192,"Méluzzine");
new Item(1193,"Clé du Bourru");
new Item(1194,"Furtok Glaciale");
new Item(1195,"Vieille clé rouillée");
new Item(1196,"Autorisation du Bois-Joli");
new Item(1197,"Clé des Mondes Ardus");
new Item(1198,"Clé piquante");
new Item(1199,"Passe-partout de Tuberculoz");
new Item(1200,"Clé des cauchemars");
new Item(1201,"Pad Sounie");
new Item(1202,"Pad Frusion 64");
new Item(1203,"Pad Game-Pyramid");
new Item(1204,"Pad Sey-Ga");
new Item(1205,"Pad Super Frusion");
new Item(1206,"Pad du Système Maitre");
new Item(1207,"Pad Frusion Entertainment System");
new Item(1208,"Manette S-Téhéf");
new Item(1209,"Canette Express");
new Item(1210,"Bouteille aux 2064 bulles");
new Item(1211,"Mousse volante");
new Item(1212,"Vin Merveilleux");
new Item(1213,"Liqueur maléfique");
new Item(1214,"Tampon MT");
new Item(1215,"Facture gratuite");
new Item(1216,"Post-It de François");
new Item(1217,"Pot à crayon solitaire");
new Item(1218,"Agrafeuse du Chaos");
new Item(1219,"Miroir bancal");
new Item(1220,"Etoile du Diable");
new Item(1221,"Poudre de plage magique");
new Item(1222,"Matériel d\'architecte");
new Item(1223,"Maquette en sable");
new Item(1224,"Winkel");
new Item(1225,"Miroir des Sables");
new Item(1226,"Etoile des Diables Jumeaux");
new Item(1227,"Sceau d\'amitié");
new Item(1228,"Insigne de l\'ordre des Ninjas");
new Item(1229,"Couteau suisse japonais");
new Item(1230,"Shuriken de second rang");
new Item(1231,"Shuriken d\'entraînement");
new Item(1232,"Najinata");
new Item(1233,"Lance-boulettes de Précision");
new Item(1234,"Ocarina chantant");
new Item(1235,"Armure de la nuit");
new Item(1236,"Insigne du Mérite");
new Item(1237,"Neige-o-glycérine");
new Item(1238,"Pass-Pyramide");
*/